persos = ["Green Knight",
          "Red Knight",
          "Blue Knight",
          "Orange Knight",
          "Grey Knight",
          "Barbarian",
          "Thief",
          "Fencer",
          "Beekeeper",
          "Industrialist",
          "Alien",
          "none",
          "Brute",
          "Snakey",
          "Saracen",
          "Royal Guard",
          "Stove",
          "Peasant",
          "Bear",
          "none",
          "Cone",
          "Civilian",
          "none",
          "Fire Demon",
          "Skeleton",
          "Icekimo",
          "Ninja"]




