persos = [["Green Knight","130px-Green_Knight_P.jpg"],
          ["Red Knight","130px-Red_Knight_P.jpg"],
          ["Blue Knight","130px-Blue_Knight_P.jpg"],
          ["Orange Knight","130px-Orange_Knight_P.jpg"],
          ["Gray Knight","130px-Gray_Knight_P.jpg"],
          ["Barbarian","130px-Gray_Knight_P.jpg"],
          ["Skeleton","130px-Skeleton_P.jpg"],
          ["Industrialist","130px-Gray_Knight_P.jpg"],
          ["Fire Demon","130px-Gray_Knight_P.jpg"],
          ["Saracen","130px-Gray_Knight_P.jpg"],
          ["Bear","130px-Gray_Knight_P.jpg"],
          ["Fencer","130px-Gray_Knight_P.jpg"],
          ["Ninjer","130px-Gray_Knight_P.jpg"],
          ["Stove Face","130px-Gray_Knight_P.jpg"],
          ["Royal Guard","130px-Royal_Guard_P.jpg"],
          ["Thief","130px-Gray_Knight_P.jpg"],
          ["Conehead","130px-Gray_Knight_P.jpg"],
          ["Peasant","130px-Gray_Knight_P.jpg"],
          ["Iceskimo","130px-Gray_Knight_P.jpg"],
          ["Killer Beekeeper","130px-Gray_Knight_P.jpg"],
          ["Snakey","130px-Gray_Knight_P.jpg"],
          ["Civilian","130px-Gray_Knight_P.jpg"],
          ["Brute","130px-Gray_Knight_P.jpg"],
          ["Alien","130px-Gray_Knight_P.jpg"]]
